### ISSUE TITLE
Connect and dictonnect without doing anything

### ISSUE THREAD

**Issue by SabatierBoris** [manoir/stormbot#3]
WARNING:slixmpp.stanza.rootstanza:You should catch IqError exceptions

**Comment by paulfariello** [comment]
Thanks for reporting.
Could you run stormbot with `-vvv` so that we have xmpp logs.
Knowing which IqError wasn't catched would help to solve this issue.

**Comment by paulfariello** [comment]
This should be fixed in develop.
